### ISSUE TITLE
url_history package?

### ISSUE THREAD

**Issue by cmoski** [tannewt/wa-law.org#16]
Hey there --

I'm working on a machine learning project in reference to the RCWs (and probably other data too, but starting with that..)

Anyway, I grabbed the script to dump the RCWs to a sqlite DB, and couldn't seem to find url_history  package in this repo. 

Probably something I'm missing, but any advice would be appreciated!

Thanks!

**Comment by cmoski** [comment]
Thought maybe the package in django-url-history, but turns out I was wrong.. (I'm primarily a C# developer 😆, please don't be too harsh!)

**Comment by tannewt** [comment]
It is here: https://github.com/tannewt/url-history I'm not sure I've posted it to pypi. You can clone that repo and do `pip install -e .` to install an editable copy.

I'm happy to post the dbs somewhere so you don't have to do the full fetch again too.

**Comment by cmoski** [comment]
@tannewt Awesome work by the way. Looking through all of this info for the first time I can see that a tremendous amount of insight into our legislative process is possible, and the amount of work to parse it out isn't trivial at all.

If you could drop the DBs somewhere that would be awesome, but by no means is it necessary. I think with that piece of information I should be able to get them fully built.

Thanks again for your hard work and the quick reply!

**Comment by tannewt** [comment]
I made a Discord server if you want to chat: https://discord.gg/r8dcfBFnyZ

Here are the db files: https://user.fm/files/v2-d3f216d8c0541cbf42cdfc909f07755f/wa-law.org.zip

I didn't upload org-website.db (used for news articles) because it is almost 5GB.
